name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v3.2.0
        with:
          curseforge-id: 452500
          modrinth-id: G9WbcGQ2
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          version-type: beta
          version: ${{ github.ref_name }}
          loaders: forge
          game-versions: 1.20.1
          java: 17
          name: ""
          changelog: "https://github.com/Buuz135/SushiGoCrafting/commits/1.20"
          dependencies: |
            titanium | depends
            patchouli | depends